# RED-BLACK TREE MODULE
# Note: this file was originally auto-generated by Google Colab.
# Renamed and cleaned for project submission.


class RBNode:
    RED   = True
    BLACK = False

    def __init__(self, data):
        self.data   = data
        self.key    = data["similarity"]   # sort key is the similarity score
        self.left   = None
        self.right  = None
        self.parent = None
        self.color  = RBNode.RED           # new nodes are always inserted as RED


class RedBlackTree:
    def __init__(self):
        self.root = None

    # ROTATIONS

    def rotate_left(self, x):
        y        = x.right
        x.right  = y.left

        if y.left:
            y.left.parent = x

        y.parent = x.parent

        if x.parent is None:
            self.root = y
        elif x == x.parent.left:
            x.parent.left  = y
        else:
            x.parent.right = y

        y.left    = x
        x.parent  = y

    def rotate_right(self, y):
        x        = y.left
        y.left   = x.right

        if x.right:
            x.right.parent = y

        x.parent = y.parent

        if y.parent is None:
            self.root = x
        elif y == y.parent.left:
            y.parent.left  = x
        else:
            y.parent.right = x

        x.right  = y
        y.parent = x

    # BST INSERT

    def bst_insert(self, root, node):
        if root is None:
            return node

        if node.key < root.key:
            root.left         = self.bst_insert(root.left, node)
            root.left.parent  = root
        else:
            root.right        = self.bst_insert(root.right, node)
            root.right.parent = root

        return root

    # INSERT + REBALANCE

    def insert(self, data):
        node      = RBNode(data)
        self.root = self.bst_insert(self.root, node)
        self._fix_insert(node)

    def _fix_insert(self, k):
        # restore Red-Black properties after insertion
        while k != self.root and k.parent.color == RBNode.RED:
            parent      = k.parent
            grandparent = parent.parent
            
            if grandparent is None:
                break

            if parent == grandparent.left:
                uncle = grandparent.right

                if uncle and uncle.color == RBNode.RED:
                    # Case 1: uncle is red -> recolor and move up
                    parent.color      = RBNode.BLACK
                    uncle.color       = RBNode.BLACK
                    grandparent.color = RBNode.RED
                    k                 = grandparent
                else:
                    if k == parent.right:
                        # Case 2: k is right child -> rotate left at parent
                        k = parent
                        self.rotate_left(k)
                    # Case 3: k is left child -> rotate right at grandparent
                    parent.color      = RBNode.BLACK
                    grandparent.color = RBNode.RED
                    self.rotate_right(grandparent)
            else:
                uncle = grandparent.left

                if uncle and uncle.color == RBNode.RED:
                    # Case 1 (mirror)
                    parent.color      = RBNode.BLACK
                    uncle.color       = RBNode.BLACK
                    grandparent.color = RBNode.RED
                    k                 = grandparent
                else:
                    if k == parent.left:
                        # Case 2 (mirror)
                        k = parent
                        self.rotate_right(k)
                    # Case 3 (mirror)
                    parent.color      = RBNode.BLACK
                    grandparent.color = RBNode.RED
                    self.rotate_left(grandparent)

        # root must always be BLACK
        self.root.color = RBNode.BLACK

    # TRAVERSAL

    def inorder(self):
        """Print all entries in ascending order of similarity score."""
        self._inorder(self.root)

    def inorder_list(self):
        """Return all entries in ascending order of similarity score."""
        result = []
        self._inorder_collect(self.root, result)
        return result

    def _inorder(self, node):
        if node:
            self._inorder(node.left)
            print(node.data)
            self._inorder(node.right)

    def _inorder_collect(self, node, result):
        if node:
            self._inorder_collect(node.left, result)
            result.append(node.data)
            self._inorder_collect(node.right, result)

    # RANGE QUERY

    def range_query(self, min_val, max_val):
        """Print all entries with similarity score in [min_val, max_val]."""
        self._range_query(self.root, min_val, max_val)

    def range_query_list(self, min_val, max_val):
        """Return all entries with similarity score in [min_val, max_val]."""
        result = []
        self._range_query_collect(self.root, min_val, max_val, result)
        return result

    def _range_query(self, node, min_val, max_val):
        if node is None:
            return

        # only go left if the left subtree could contain values >= min_val
        if min_val < node.key:
            self._range_query(node.left, min_val, max_val)

        if min_val <= node.key <= max_val:
            print(node.data)

        # only go right if the right subtree could contain values <= max_val
        if node.key < max_val:
            self._range_query(node.right, min_val, max_val)

    def _range_query_collect(self, node, min_val, max_val, result):
        if node is None:
            return

        if min_val < node.key:
            self._range_query_collect(node.left, min_val, max_val, result)

        if min_val <= node.key <= max_val:
            result.append(node.data)

        if node.key < max_val:
            self._range_query_collect(node.right, min_val, max_val, result)


"""
RED-BLACK TREE NOTES

PURPOSE:
    Provides an optional BST-based structure for storing and querying
    similarity results by score range. Useful for answering questions such as
    "which pairs have similarity between 0.6 and 0.8?"

    This is a bonus data structure beyond the minimum project requirements.
    The core pipeline (loading -> preprocessing -> hashing -> Jaccard ->
    merge sort -> display) does not depend on this module.

RED-BLACK TREE PROPERTIES (maintained after every insert)

    1. Every node is either RED or BLACK.
    2. The root is always BLACK.
    3. No two consecutive RED nodes (a RED node's parent must be BLACK).
    4. Every path from a node to a NULL leaf has the same number of BLACK nodes.

    These properties guarantee the tree height stays O(log n),
    ensuring O(log n) insert and search.

NODE STRUCTURE

    Each RBNode stores:
        data       : full similarity record dict {"doc1", "doc2", "similarity"}
        key        : data["similarity"] used as the BST sort key
        color      : RED or BLACK
        left/right : child pointers
        parent     : parent pointer (required for fix_insert rotations)

INSERT

    Step 1: bst_insert() — standard BST insertion by key.
    Step 2: _fix_insert() — restores Red-Black properties via recoloring
            and at most 2 rotations (O(log n) recoloring steps).

    Time: O(log n)

ROTATIONS

    rotate_left(x) and rotate_right(y) restructure local subtrees
    without violating BST ordering. They are the building block for
    all rebalancing operations.

INORDER TRAVERSAL

    Visits nodes in ascending key (score) order.
    Time: O(n)

RANGE QUERY

    Finds all document pairs with similarity score in [min_val, max_val].
    Prunes subtrees that cannot contain values in range:
        - skips left subtree if min_val >= node.key
        - skips right subtree if max_val <= node.key
    Time: O(log n + k)   k = number of matches

HOW TO USE IN MAIN

    rbt = RedBlackTree()
    for doc1, doc2, score in sorted_results:
        rbt.insert({"doc1": doc1, "doc2": doc2, "similarity": score})

    # print all HIGH similarity pairs
    rbt.range_query(0.8, 1.0)

TIME COMPLEXITY SUMMARY

    Insert:       O(log n)
    Inorder:      O(n)
    Range query:  O(log n + k)

SPACE COMPLEXITY

    O(n)   one node per similarity pair


"""
